var board=[
    'JTIYKPNBTBEARZP',
    'QNYUEIAAVMRFNOK',
    'KARRUKKNETAKLRC',
    'EHLGGRNFDAFAIMG',
    'JPNSEGROAARNOIL',
    'QENELIRVMBKROTS',
    'PLMYARSEEKAYVXL',
    'ZEIGOATAGLTEEYC',
    'QCPLPFRNLILZHJI',
    'YFVHOFSIMLTESBZ',
    'GZXJKEGWTGCDJFB',
    'TCADMAVPEOTYORI',
    'COYVTOHKNEAYJOU',
    'REPOUVKHKBBDJGV',
    'HIRETAUNAZCOPUH',
    ];
var solutions=[
    [6,10,14,2],
    [0,9,0,12],
    [7,1,0,1],
    [10,13,13,13],
    [4,5,10,5]
];